version: 0.0
os: linux

files:
  - source: scripts/
    destination: /home/ec2-user/codedeploy/scripts
  - source: IMAGE_TAG.txt
    destination: /home/ec2-user/codedeploy/scripts/IMAGE_TAG.txt

hooks:
  BeforeInstall:
    - location: scripts/stop.sh
      timeout: 300
      runas: ec2-user

  AfterInstall:
    - location: scripts/install.sh
      timeout: 300
      runas: ec2-user

  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300
      runas: ec2-user