version: 0.2

env:
  variables:
    ECR_REPO_NAME: "jibijoa-backend"
    AWS_ACCOUNT_ID: "121568407787"
    AWS_REGION: "ap-southeast-2"
    ECR_URI: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO_NAME}"

phases:
  pre_build:
    commands:
      - echo "Resolving commit hash..."
      - export COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - echo "COMMIT_HASH: $COMMIT_HASH"

      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t ${ECR_URI}:${COMMIT_HASH} .

  post_build:
    commands:
      - echo "Pushing image to ECR..."
      - docker push ${ECR_URI}:${COMMIT_HASH}

      - echo "Creating imagedefinitions.json..."
      - printf '[{"name":"fastapi-backend","imageUri":"%s"}]' "${ECR_URI}:${COMMIT_HASH}" > imagedefinitions.json
      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json