version: 0.2
phases:
  pre_build:
    commands:
      # 환경 변수 정의
      - export ECR_REPO_NAME=jibijoa-backend
      - export AWS_ACCOUNT_ID=121568407787
      - export AWS_REGION=ap-southeast-2
      - export ECR_URI=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO_NAME}
      
      # COMMIT_HASH 추출
      - echo "Resolving commit hash..."
      - export COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - echo "COMMIT_HASH=$COMMIT_HASH"
      
      # ECR 로그인
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${ECR_URI}
      
  build:
    commands:
      # Docker 이미지 빌드
      - echo "Building Docker image..."
      - docker build -t ${ECR_URI}:${COMMIT_HASH} -t ${ECR_URI}:latest .
      
  post_build:
    commands:
      # ECR 푸시
      - echo "Pushing image to ECR..."
      - docker push ${ECR_URI}:${COMMIT_HASH}
      - docker push ${ECR_URI}:latest
      
      # IMAGE_TAG를 파일로 저장 (scripts 디렉토리)
      - echo "Saving IMAGE_TAG to file..."
      - echo "${COMMIT_HASH}" > scripts/IMAGE_TAG.txt
      - cat scripts/IMAGE_TAG.txt
      
      # 스크립트 파일 확인 및 권한 부여
      - echo "Preparing deployment scripts..."
      - ls -la
      - ls -la scripts/ 2>/dev/null || echo "scripts directory not found"
      - chmod +x scripts/*.sh 2>/dev/null || true
artifacts:
  files:
    - appspec.yml
    - scripts/**/*